### PR TITLE
completely overhaul build system

### PR DESCRIPTION
**Pull request by jo-m**
The old build system was very convoluted and overly complicated. The reason for this was its ability to compile to Javascript: this required local compilation of all the dependencies, so we could then feed the LLVM bytecode to Emscripten. With this functionality removed, the build system can be simplified.

This PR
* replaces the old mix of CMake, shell scripts and Docker files with modern CMake
* installs dependencies via OS package manager where possible (flatbuffers is the only exception)
* enables out of tree builds
* simplifies the docker file

This makes it easy to compile and run on any recent Linux distro.

Tests were run on Ubuntu 18.04 and completed without error.

### CODE REVIEW

**Comment by clementnuss** [comment]
Excellent work !
I have tested it and it works flawlessly on my side (the Dockerfile and a "manual" compilation, in WSL Ubuntu 18.04).
The CMake FindModule feature is extremly useful in this case 👍

**Comment by ogivuk** [comment]
Thanks jo-m for the great work, and thanks Clement for testing it. I vote that we perform the merge.
Thomas, any comments?

**Comment by jo-m** [comment]
@thomaslocher this ok to merge?

**Comment by thomaslocher** [comment]
Yes, it is okay to merge. Sorry for the delay!

**Comment by jo-m** [comment]
cool thanks!

**Pull request merged**
